// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Order.Infrastructure.Persistence;

#nullable disable

namespace Order.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260506194728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order.Domain.Entities.BakeryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-2222-3333-444455556666"),
                            CustomerName = "Alice Baker",
                            OrderDate = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("d3b4e7e4-23fb-47df-bc6c-18a0ea12cb24"),
                            Quantity = 2,
                            Status = "Completed",
                            TotalPrice = 7.00m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-3333-4444-555566667777"),
                            CustomerName = "Bob Dough",
                            OrderDate = new DateTime(2026, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("f2e1a3b4-64df-41ca-87ab-51b1f2e2ac89"),
                            Quantity = 1,
                            Status = "Placed",
                            TotalPrice = 6.00m
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-3333-4444-5555-666677778888"),
                            CustomerName = "Claire Crust",
                            OrderDate = new DateTime(2026, 3, 10, 9, 15, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("e8a21d5a-1c7c-47db-93ab-62c1e7f3d91b"),
                            Quantity = 3,
                            Status = "Cancelled",
                            TotalPrice = 12.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
